Translate to Chinese
Euphillya/Skyllia pull request #16
Opened 2024-01-24 07:21 UTC by haha252

The wiki I will upload soon.

2024-01-24 07:24 UTC, haha252 commented
The Wiki
[安装方式(Installation du plugins).md](https://github.com/Euphillya/Skyllia/files/14034824/Installation.du.plugins.md)
[运作方式(Fonctionnement du plugin).md](https://github.com/Euphillya/Skyllia/files/14034829/Fonctionnement.du.plugin.md)
[权限管理(Permissions Standard du Plugin Skyllia).md](https://github.com/Euphillya/Skyllia/files/14034838/Permissions.Standard.du.Plugin.Skyllia.md)

2024-01-24 18:32 UTC, Euphillya commented
Create a wiki folder at the plugin source, which will be used to store future languages as follows: 
wiki/lang/all_files

And we'll put all the wikis in the readme.md with a clickable link.

2024-01-25 01:57 UTC, haha252 commented
Like this?

2024-01-25 04:48 UTC, Euphillya commented
Yes, ans résolve conflict with readme :)

2024-01-25 04:53 UTC, haha252 commented
Emmmm, I edited readme.md 
add a clickable button to Chinese readme file(readme_zh.md)

2024-01-25 05:31 UTC, Euphillya commented
Configurations are no longer in the readme

2024-01-27 06:20 UTC, haha252 commented
finished

2024-01-27 11:06 UTC, haha252 commented
How About this one

2024-01-27 19:18 UTC, Euphillya requested changes
Change that so I can start importing.Cliquez pour utiliser cette solution

2024-01-27 19:18 UTC, Euphillya commented on readme_zh.md
> +```
Create the wiki page for this.

2024-02-01 13:45 UTC, haha252 commented
awa

2024-02-01 13:46 UTC, haha252 commented on readme_zh.md
> +```
ok for a moment

2024-02-01 13:49 UTC, haha252 commented
ok finished

2024-02-02 16:06 UTC, Euphillya commented
It's not up to date with the new configs and API, but it'll be good enough!

2024-02-02 16:07 UTC, merged